spring:
  application:
    name: authorization-service
  security:
    oauth2:
      authorizationserver:
        client:
          dizi-cloud:
            registration:
              client-id: "dizi-web-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8081/login/oauth2/code/dizi-cloud"
              scopes:
                - writeIngredients
                - deleteIngredients
                - openid
            require-authorization-consent: true

    user:
      name: "homayoun"
      password: "{noop}secret"

logging:
  level:
    com.dizi.dz.controller: INFO
    org.springframework.security: trace

server:
  port: 9000